config/routes.rb
Rails.application.routes.draw do
  resources :sys_configs

  resources :types

  resources :names

  resources :notes do
    member do
      get 'pub'
    end
  end

  get "help", to: "help#index"

  devise_for :auth, :class_name => User, :controllers => {:sessions => 'auth/sessions'}

  root 'home#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates_presence_of :note_title
  validates_uniqueness_of :note_title, :scope => [:user_id, :deleted, :deleted_at]

  def published?
    self.published == 1
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  skip_before_filter :authenticate_auth!, only: [:pub]
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def pub
    @note = Note.where(:id => params[:id], :published => 1, :deleted => 0).first
    @read_only = true
    render :show
  end

  # GET /notes
  def index
    @notes = Note.all.where(deleted: 0, user_id: current_user.id).page(params[:page]).per(current_user.per_page)
  end

  # GET /notes/1
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.note_contents = "{\"rootKeyword\":\"#{@note.note_title}\",\"keywords\":{\"#{@note.note_title}\":[]}}"

    if @note.save
      #redirect_to @note, notice: 'Note was successfully created.'
      redirect_to @note
    else
      render :new
    end
  end

  # PATCH/PUT /notes/1
  def update
    @note.attributes = note_params
    respond_to do |format|
      if @note.save
        format.html {redirect_to @note, notice: 'Note was successfully updated.'}
        format.json {render :text => @note.lock_version.to_s, :layout => false}
      else
        format.html {render :edit }
        format.json {render :text => 'NG', :layout => false, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /notes/1
  def destroy
    @note.deleted = 9
    @note.deleted_at = Time.now
    @note.updated_user = current_user.login
    @note.save!
    redirect_to notes_url, notice: t('view.notes.note_was_successfully_destroyed')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.where(:id => params[:id], :user_id => current_user.id, :deleted => 0).first
    end

    # Only allow a trusted parameter "white list" through.
    def note_params
      params.require(:note).permit(:note_title, :note_contents, :published, :lock_version)
    end
end

app/helpers/notes_helper.rb
# -*- encoding: utf-8 -*-
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
<%= hidden_field_tag 'back_to', back_to %>
<%= f.hidden_field :lock_version %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-8">
<div class="form-group">
  <%= f.label :note_title %> (<%=t("view.notes._form.your_thinking_theme")%>)
  <%= f.text_field :note_title, {:class => "form-control"} %>
</div>
  <%= f.submit :class => "btn btn-primary btn-md" %>
  <%= link_or_back t('view.back'), notes_path, :class => "btn btn-default btn-md" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1><%= getLongName('table_name','notes')%> の編集</h1>

<%= render 'form' %>

<%= link_or_back '戻る', notes_path %>

app/views/notes/index.html.erb
<% if @notes.empty? %>
  <div class="jumbotron">
    <%= content_tag :h1, t('view.notes.index.3dmind_will') %>
    <%= content_tag :p, t('view.notes.index.3dmind_will_detail') %>
    <p>
    <%= back_to_link t('view.notes.index.open_new_note'), new_note_path, :class => "btn btn-primary btn-lg", :role=>"button" %>
    <%= back_to_link t('view.notes.index.to_help'), {:controller => :help}, {:class => "btn btn-warning btn-lg", :role=>"button"} %>
    </p>
  </div>
<% else %>
  <div class="col-md-8">
  <div class="panel panel-default">
    <!-- Default panel contents -->
  <div class="panel-heading">Your notes.</div>
  <div class="list-group">
    <% @notes.each do |note| %>
      <li class="list-group-item"><div class="row"><%=back_to_link "<div class='col-md-11'>#{h note.note_title}#{note.published? ? " <span class='label label-default'>Shared</span>" : ""}</div>".html_safe, note_path(note) %><div class="col-md-1"><%= link_to '<i class="glyphicon glyphicon-remove-circle"></i>'.html_safe, note_path(note), :method => :delete, :data => {:confirm => t("view.notes.index.delete_this_note?")} %></div></div></li>
    <% end %>
  </div>
</div>
  <div class="list-group">
  <p>
    <%= back_to_link "<i class='glyphicon glyphicon-file'></i> #{t "view.notes.new.create_new_note"}".html_safe, new_note_path, :class => "btn btn-primary btn-md", :role=>"button" %>
    </p>
  </div>
</div>
<% end %>

app/views/notes/new.html.erb
<%= content_tag :h1, t('view.notes.new.create_new_note') %>

<%= render 'form' %>

app/views/notes/show.html.erb
<div id="note-container" note_id="<%=@note.id%>" note_url="<%=@read_only ? pub_note_path(@note, :json) : note_path(@note, :json)%>" lock_version="<%=@note.lock_version%>" published="<%=@note.published%>" read_only="<%=@read_only ? "1" : "0" %>">
    <% if !@read_only %><input type="text" id='inputbox' placeholder="Input some words"><%end%><div id="breadcrumb" <%= @read_only ? "style='left:0px;'".html_safe : "style='left:230px;'".html_safe%>></div>
    <% if !@read_only %>
      <div id="published_url" style="<%= @note.published? ? "" : "display:none"%>"><%=t "view.notes.show.published_url"%>: <input type="text" value="<%=pub_note_path(@note, :only_path => false)%>"></div>
        <input type="button" id='publish_button' confirm_message="<%=t("view.notes.show.confirm_message")%>" un="<%=t("view.notes.show.un")%>" publish_value="<%= t("view.notes.show.publish")%>" unpublish_value="<%= t("view.notes.show.unpublish")%>" value="<%=@note.published? ? t("view.notes.show.unpublish") : t("view.notes.show.publish") %>" class="btn btn-info btn-md">
        <input type="button" id='save_button' value="<%=t("view.notes.show.save")%>" class="btn btn-primary btn-md">
    <% end %>
</div>
<span id="js_messages" style="display:none"
  confirm_message="<%=t("view.notes.show.confirm_message")%>"
  un="<%=t("view.notes.show.un")%>"
  publish_value="<%= t("view.notes.show.publish")%>"
  unpublish_value="<%= t("view.notes.show.unpublish")%>"
  complete_message="<%=t("view.notes.show.complete_message")%>"
  save_was_completed="<%=t("view.notes.show.save_was_completed")%>"
  keyword_was_existed="<%=t("view.notes.show.keyword_was_existed")%>"
  ></span> 