config/routes.rb
Rails.application.routes.draw do
  resources :sys_configs

  resources :types

  resources :names

  resources :notes do
    member do
      get 'pub'
    end
  end

  get "help", to: "help#index"

  devise_for :auth, :class_name => User, :controllers => {:sessions => 'auth/sessions'}

  root 'home#index'

end

app/models/sys_config.rb
class SysConfig < ActiveRecord::Base
end

app/controllers/sys_configs_controller.rb
class SysConfigsController < ApplicationController
  before_action :set_sys_config, only: [:show, :edit, :update, :destroy]

  # GET /sys_configs
  def index
    @sys_configs = SysConfig.all
  end

  # GET /sys_configs/1
  def show
  end

  # GET /sys_configs/new
  def new
    @sys_config = SysConfig.new
  end

  # GET /sys_configs/1/edit
  def edit
  end

  # POST /sys_configs
  def create
    @sys_config = SysConfig.new(sys_config_params)

    if @sys_config.save
      redirect_to @sys_config, notice: 'Sys config was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sys_configs/1
  def update
    if @sys_config.update(sys_config_params)
      redirect_to @sys_config, notice: 'Sys config was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sys_configs/1
  def destroy
    @sys_config.destroy
    redirect_to sys_configs_url, notice: 'Sys config was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sys_config
      @sys_config = SysConfig.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sys_config_params
      params.require(:sys_config).permit(:config_section, :config_key, :value1, :value2, :value3, :value_long, :config_description_text)
    end
end

app/helpers/sys_configs_helper.rb
# -*- encoding: utf-8 -*-
module SysConfigsHelper
end

app/views/sys_configs/_form.html.erb
<%= form_for(@sys_config) do |f| %>
<%= hidden_field_tag 'back_to', back_to %>
<%= f.hidden_field :lock_version %>
  <% if @sys_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sys_config.errors.count, "error") %> prohibited this sys_config from being saved:</h2>

      <ul>
      <% @sys_config.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="form_table">
  <tr>
    <th><%= f.label :config_section, getLongName('sys_configs', 'config_section') %></th>
    <td><%= f.text_field :config_section %></td>
  </tr>
  <tr>
    <th><%= f.label :config_key, getLongName('sys_configs', 'config_key') %></th>
    <td><%= f.text_field :config_key %></td>
  </tr>
  <tr>
    <th><%= f.label :value1, getLongName('sys_configs', 'value1') %></th>
    <td><%= f.text_field :value1 %></td>
  </tr>
  <tr>
    <th><%= f.label :value2, getLongName('sys_configs', 'value2') %></th>
    <td><%= f.text_field :value2 %></td>
  </tr>
  <tr>
    <th><%= f.label :value3, getLongName('sys_configs', 'value3') %></th>
    <td><%= f.text_field :value3 %></td>
  </tr>
  <tr>
    <th><%= f.label :value_long, getLongName('sys_configs', 'value_long') %></th>
    <td><%= f.text_field :value_long %></td>
  </tr>
  <tr>
    <th><%= f.label :config_description_text, getLongName('sys_configs', 'config_description_text') %></th>
    <td><%= f.text_field :config_description_text %></td>
  </tr>
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sys_configs/edit.html.erb
<h1><%= getLongName('table_name','sys_configs')%> の編集</h1>

<%= render 'form' %>

<%= link_or_back '戻る', sys_configs_path %>

app/views/sys_configs/index.html.erb
<h1><%= getLongName('table_name','sys_configs')%> 一覧</h1>

<%= paginate(@sys_configs) %>

<table class="list_table table-bordered table-hover">
  <tr>
    <th><%= getLongName('sys_configs', 'config_section') %></th>
    <th><%= getLongName('sys_configs', 'config_key') %></th>
    <th><%= getLongName('sys_configs', 'value1') %></th>
    <th><%= getLongName('sys_configs', 'value2') %></th>
    <th><%= getLongName('sys_configs', 'value3') %></th>
    <th><%= getLongName('sys_configs', 'value_long') %></th>
    <th><%= getLongName('sys_configs', 'config_description_text') %></th>
  </tr>

<% @sys_configs.each do |sys_config| %>
  <tr>
    <td><%= back_to_link sys_config.config_section, sys_config %></td>
    <td><%= sys_config.config_key %></td>
    <td><%= sys_config.value1 %></td>
    <td><%= sys_config.value2 %></td>
    <td><%= sys_config.value3 %></td>
    <td><%= sys_config.value_long %></td>
    <td><%= sys_config.config_description_text %></td>
  </tr>
<% end %>
</table>

<br />

<%= paginate(@sys_configs) %>

<%= back_to_link getLongName('table_name','sys_configs') + ' の新規作成', new_sys_config_path %>

app/views/sys_configs/new.html.erb
<h1><%= getLongName('table_name','sys_configs')%> の新規作成</h1>

<%= render 'form' %>

<%= link_or_back '戻る', sys_configs_path %>

app/views/sys_configs/show.html.erb
<h1><%= getLongName('table_name','sys_configs')%> 詳細</h1>

<table class="show_table">
  <tr>
    <th><%= getLongName('sys_configs', 'config_section') %></th>
    <td><%= @sys_config.config_section %></td>
  </tr>
  <tr>
    <th><%= getLongName('sys_configs', 'config_key') %></th>
    <td><%= @sys_config.config_key %></td>
  </tr>
  <tr>
    <th><%= getLongName('sys_configs', 'value1') %></th>
    <td><%= @sys_config.value1 %></td>
  </tr>
  <tr>
    <th><%= getLongName('sys_configs', 'value2') %></th>
    <td><%= @sys_config.value2 %></td>
  </tr>
  <tr>
    <th><%= getLongName('sys_configs', 'value3') %></th>
    <td><%= @sys_config.value3 %></td>
  </tr>
  <tr>
    <th><%= getLongName('sys_configs', 'value_long') %></th>
    <td><%= @sys_config.value_long %></td>
  </tr>
  <tr>
    <th><%= getLongName('sys_configs', 'config_description_text') %></th>
    <td><%= @sys_config.config_description_text %></td>
  </tr>
</table>

<%= back_to_link '編集', edit_sys_config_path(@sys_config) %> |
<%= link_to 'Destroy', sys_config, method: :delete, data: { confirm: '削除します。よろしいですか?' } %> |
<%= link_or_back '戻る', sys_configs_path %>