config/routes.rb
Rails.application.routes.draw do
  resources :sys_configs

  resources :types

  resources :names

  resources :notes do
    member do
      get 'pub'
    end
  end

  get "help", to: "help#index"

  devise_for :auth, :class_name => User, :controllers => {:sessions => 'auth/sessions'}

  root 'home#index'

end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  def index
    @names = Name.all
  end

  # GET /names/1
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  def create
    @name = Name.new(name_params)

    if @name.save
      redirect_to @name, notice: 'Name was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /names/1
  def update
    if @name.update(name_params)
      redirect_to @name, notice: 'Name was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /names/1
  def destroy
    @name.destroy
    redirect_to names_url, notice: 'Name was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def name_params
      params.require(:name).permit(:name_locale, :name_section, :name_key, :long_name, :short_name, :other_name, :name_description)
    end
end

app/helpers/names_helper.rb
# -*- encoding: utf-8 -*-
module NamesHelper
end

app/views/names/_form.html.erb
<%= form_for(@name) do |f| %>
<%= hidden_field_tag 'back_to', back_to %>
<%= f.hidden_field :lock_version %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="form_table">
  <tr>
    <th><%= f.label :name_locale, getLongName('names', 'name_locale') %></th>
    <td><%= f.text_field :name_locale %></td>
  </tr>
  <tr>
    <th><%= f.label :name_section, getLongName('names', 'name_section') %></th>
    <td><%= f.text_field :name_section %></td>
  </tr>
  <tr>
    <th><%= f.label :name_key, getLongName('names', 'name_key') %></th>
    <td><%= f.text_field :name_key %></td>
  </tr>
  <tr>
    <th><%= f.label :long_name, getLongName('names', 'long_name') %></th>
    <td><%= f.text_field :long_name %></td>
  </tr>
  <tr>
    <th><%= f.label :short_name, getLongName('names', 'short_name') %></th>
    <td><%= f.text_field :short_name %></td>
  </tr>
  <tr>
    <th><%= f.label :other_name, getLongName('names', 'other_name') %></th>
    <td><%= f.text_field :other_name %></td>
  </tr>
  <tr>
    <th><%= f.label :name_description, getLongName('names', 'name_description') %></th>
    <td><%= f.text_field :name_description %></td>
  </tr>
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1><%= getLongName('table_name','names')%> の編集</h1>

<%= render 'form' %>

<%= link_or_back '戻る', names_path %>

app/views/names/index.html.erb
<h1><%= getLongName('table_name','names')%> 一覧</h1>

<%= paginate(@names) %>

<table class="list_table table-bordered table-hover">
  <tr>
    <th><%= getLongName('names', 'name_locale') %></th>
    <th><%= getLongName('names', 'name_section') %></th>
    <th><%= getLongName('names', 'name_key') %></th>
    <th><%= getLongName('names', 'long_name') %></th>
    <th><%= getLongName('names', 'short_name') %></th>
    <th><%= getLongName('names', 'other_name') %></th>
    <th><%= getLongName('names', 'name_description') %></th>
  </tr>

<% @names.each do |name| %>
  <tr>
    <td><%= back_to_link name.name_locale, name %></td>
    <td><%= name.name_section %></td>
    <td><%= name.name_key %></td>
    <td><%= name.long_name %></td>
    <td><%= name.short_name %></td>
    <td><%= name.other_name %></td>
    <td><%= name.name_description %></td>
  </tr>
<% end %>
</table>

<br />

<%= paginate(@names) %>

<%= back_to_link getLongName('table_name','names') + ' の新規作成', new_name_path %>

app/views/names/new.html.erb
<h1><%= getLongName('table_name','names')%> の新規作成</h1>

<%= render 'form' %>

<%= link_or_back '戻る', names_path %>

app/views/names/show.html.erb
<h1><%= getLongName('table_name','names')%> 詳細</h1>

<table class="show_table">
  <tr>
    <th><%= getLongName('names', 'name_locale') %></th>
    <td><%= @name.name_locale %></td>
  </tr>
  <tr>
    <th><%= getLongName('names', 'name_section') %></th>
    <td><%= @name.name_section %></td>
  </tr>
  <tr>
    <th><%= getLongName('names', 'name_key') %></th>
    <td><%= @name.name_key %></td>
  </tr>
  <tr>
    <th><%= getLongName('names', 'long_name') %></th>
    <td><%= @name.long_name %></td>
  </tr>
  <tr>
    <th><%= getLongName('names', 'short_name') %></th>
    <td><%= @name.short_name %></td>
  </tr>
  <tr>
    <th><%= getLongName('names', 'other_name') %></th>
    <td><%= @name.other_name %></td>
  </tr>
  <tr>
    <th><%= getLongName('names', 'name_description') %></th>
    <td><%= @name.name_description %></td>
  </tr>
</table>

<%= back_to_link '編集', edit_name_path(@name) %> |
<%= link_to 'Destroy', name, method: :delete, data: { confirm: '削除します。よろしいですか?' } %> |
<%= link_or_back '戻る', names_path %>