config/routes.rb
Rails.application.routes.draw do
  resources :sys_configs

  resources :types

  resources :names

  resources :notes do
    member do
      get 'pub'
    end
  end

  get "help", to: "help#index"

  devise_for :auth, :class_name => User, :controllers => {:sessions => 'auth/sessions'}

  root 'home#index'

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  def index
    @types = Type.all
  end

  # GET /types/1
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  def create
    @type = Type.new(type_params)

    if @type.save
      redirect_to @type, notice: 'Type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /types/1
  def update
    if @type.update(type_params)
      redirect_to @type, notice: 'Type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /types/1
  def destroy
    @type.destroy
    redirect_to types_url, notice: 'Type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def type_params
      params.require(:type).permit(:type_section, :type_key, :long_name, :short_name, :other_name, :type_description, :type_description_text, :display_order1, :display_order2, :logic_bind_type)
    end
end

app/helpers/types_helper.rb
# -*- encoding: utf-8 -*-
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
<%= hidden_field_tag 'back_to', back_to %>
<%= f.hidden_field :lock_version %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="form_table">
  <tr>
    <th><%= f.label :type_section, getLongName('types', 'type_section') %></th>
    <td><%= f.text_field :type_section %></td>
  </tr>
  <tr>
    <th><%= f.label :type_key, getLongName('types', 'type_key') %></th>
    <td><%= f.text_field :type_key %></td>
  </tr>
  <tr>
    <th><%= f.label :long_name, getLongName('types', 'long_name') %></th>
    <td><%= f.text_field :long_name %></td>
  </tr>
  <tr>
    <th><%= f.label :short_name, getLongName('types', 'short_name') %></th>
    <td><%= f.text_field :short_name %></td>
  </tr>
  <tr>
    <th><%= f.label :other_name, getLongName('types', 'other_name') %></th>
    <td><%= f.text_field :other_name %></td>
  </tr>
  <tr>
    <th><%= f.label :type_description, getLongName('types', 'type_description') %></th>
    <td><%= f.text_field :type_description %></td>
  </tr>
  <tr>
    <th><%= f.label :type_description_text, getLongName('types', 'type_description_text') %></th>
    <td><%= f.text_field :type_description_text %></td>
  </tr>
  <tr>
    <th><%= f.label :display_order1, getLongName('types', 'display_order1') %></th>
    <td><%= f.number_field :display_order1 %></td>
  </tr>
  <tr>
    <th><%= f.label :display_order2, getLongName('types', 'display_order2') %></th>
    <td><%= f.number_field :display_order2 %></td>
  </tr>
  <tr>
    <th><%= f.label :logic_bind_type, getLongName('types', 'logic_bind_type') %></th>
    <td><%= f.text_field :logic_bind_type %></td>
  </tr>
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1><%= getLongName('table_name','types')%> の編集</h1>

<%= render 'form' %>

<%= link_or_back '戻る', types_path %>

app/views/types/index.html.erb
<h1><%= getLongName('table_name','types')%> 一覧</h1>

<%= paginate(@types) %>

<table class="list_table table-bordered table-hover">
  <tr>
    <th><%= getLongName('types', 'type_section') %></th>
    <th><%= getLongName('types', 'type_key') %></th>
    <th><%= getLongName('types', 'long_name') %></th>
    <th><%= getLongName('types', 'short_name') %></th>
    <th><%= getLongName('types', 'other_name') %></th>
    <th><%= getLongName('types', 'type_description') %></th>
    <th><%= getLongName('types', 'type_description_text') %></th>
    <th><%= getLongName('types', 'display_order1') %></th>
    <th><%= getLongName('types', 'display_order2') %></th>
    <th><%= getLongName('types', 'logic_bind_type') %></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= back_to_link type.type_section, type %></td>
    <td><%= type.type_key %></td>
    <td><%= type.long_name %></td>
    <td><%= type.short_name %></td>
    <td><%= type.other_name %></td>
    <td><%= type.type_description %></td>
    <td><%= type.type_description_text %></td>
    <td><%= type.display_order1 %></td>
    <td><%= type.display_order2 %></td>
    <td><%= type.logic_bind_type %></td>
  </tr>
<% end %>
</table>

<br />

<%= paginate(@types) %>

<%= back_to_link getLongName('table_name','types') + ' の新規作成', new_type_path %>

app/views/types/new.html.erb
<h1><%= getLongName('table_name','types')%> の新規作成</h1>

<%= render 'form' %>

<%= link_or_back '戻る', types_path %>

app/views/types/show.html.erb
<h1><%= getLongName('table_name','types')%> 詳細</h1>

<table class="show_table">
  <tr>
    <th><%= getLongName('types', 'type_section') %></th>
    <td><%= @type.type_section %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'type_key') %></th>
    <td><%= @type.type_key %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'long_name') %></th>
    <td><%= @type.long_name %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'short_name') %></th>
    <td><%= @type.short_name %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'other_name') %></th>
    <td><%= @type.other_name %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'type_description') %></th>
    <td><%= @type.type_description %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'type_description_text') %></th>
    <td><%= @type.type_description_text %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'display_order1') %></th>
    <td><%= @type.display_order1 %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'display_order2') %></th>
    <td><%= @type.display_order2 %></td>
  </tr>
  <tr>
    <th><%= getLongName('types', 'logic_bind_type') %></th>
    <td><%= @type.logic_bind_type %></td>
  </tr>
</table>

<%= back_to_link '編集', edit_type_path(@type) %> |
<%= link_to 'Destroy', type, method: :delete, data: { confirm: '削除します。よろしいですか?' } %> |
<%= link_or_back '戻る', types_path %>